"""Add priority column to Task table

Revision ID: 133d2a2e1819
Revises: 96eb60828041
Create Date: 2025-10-07 03:24:45.151228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133d2a2e1819'
down_revision = '96eb60828041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('user')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))
        #batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        #batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        #batch_op.drop_constraint(batch_op.f('fk_task_user_id_user'), type_='foreignkey')
        #batch_op.create_foreign_key(batch_op.f('fk_task_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        #batch_op.drop_constraint(batch_op.f('fk_task_user_id_users'), type_='foreignkey')
        #batch_op.create_foreign_key(batch_op.f('fk_task_user_id_user'), 'user', ['user_id'], ['id'])
        #batch_op.drop_column('updated_at')
        #batch_op.drop_column('created_at')
        batch_op.drop_column('priority')

    #op.create_table('user',
    #sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    #sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    #sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    #sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    #sa.UniqueConstraint('username', name=op.f('uq_user_username'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    #)
    # ### end Alembic commands ###
