"""Add is_completed column (nullable)

Revision ID: 710177df158f
Revises: a2d4180d3159
Create Date: 2025-09-01 04:25:29.894708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710177df158f'
down_revision = 'a2d4180d3159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=True))
        batch_op.drop_column('done')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###
