"""Set is_completed to NOT NULL and fill null values

Revision ID: 96eb60828041
Revises: 710177df158f
Create Date: 2025-09-01 04:27:31.758724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96eb60828041'
down_revision = '710177df158f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:

        batch_op.execute("UPDATE task SET is_completed = False WHERE is_completed IS NULL")
        
        batch_op.alter_column('is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
