"""Add created_at and updated_at to Task

Revision ID: bac6756d90c1
Revises: 133d2a2e1819
Create Date: 2025-10-07 03:37:10.830495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = 'bac6756d90c1'
down_revision = '133d2a2e1819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('user')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        #batch_op.drop_constraint(batch_op.f('fk_task_user_id_user'), type_='foreignkey')
        #batch_op.create_foreign_key(batch_op.f('fk_task_user_id_users'), 'users', ['user_id'], ['id'])
    op.execute(
        "UPDATE task SET created_at = NOW(), updated_at = NOW() WHERE created_at IS NULL"
    )

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('created_at',
                              existing_type=sa.DateTime(),
                              nullable=False)
        batch_op.alter_column('updated_at',
                              existing_type=sa.DateTime(),
                              nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
       # batch_op.drop_constraint(batch_op.f('fk_task_user_id_users'), type_='foreignkey')
        #batch_op.create_foreign_key(batch_op.f('fk_task_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    #op.create_table('user',
    #sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    #sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    #sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    #sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    #sa.UniqueConstraint('username', name=op.f('uq_user_username'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    #)
    # ### end Alembic commands ###
